version: "3.9"

services:
    web: 
        build: .
        container_name: email-handler
        ports:
          -  "8000:8000"
        env_file:
          -  ".env"
        depends_on:
          -  "db"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000/"]
            interval: 30s
            timeout: 5s
            retries: 5
    
    db:
        image: postgres:15
        container_name: EmailHandlerDb
        restart: unless-stopped
        volumes:
          -  EmailHandlerVolume:/var/lib/postgresql/data
        environment:
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_DB: ${POSTGRES_DB}
        
volumes:
    EmailHandlerVolume: